config/routes.rb
Rails.application.routes.draw do
  resources :bookings
  resources :libraries
  resources :books
  resources :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/library.rb
class Library < ApplicationRecord
    has_many :books
end

app/controllers/libraries_controller.rb
class LibrariesController < ApplicationController
  before_action :set_library, only: %i[ show edit update destroy ]

  # GET /libraries or /libraries.json
  def index
    @libraries = Library.includes(books: [:bookings, :users])
    data = {libraries: []}
    @libraries.each do |library|
      sub_data = { library: library }
      books = []
      library.books.each do |book|
        books << {name: book.name, remaining_quantity: book.remaining_quantity, total_quantity: book.quantity, users_who_brrows: book.users }
      end
      data[:libraries] << { library: library, books: books}
    end
    render json: data
  end

  # GET /libraries/1 or /libraries/1.json
  def show
  end

  # GET /libraries/new
  def new
    @library = Library.new
  end

  # GET /libraries/1/edit
  def edit
  end

  # POST /libraries or /libraries.json
  def create
    @library = Library.new(library_params)

    respond_to do |format|
      if @library.save
        format.html { redirect_to library_url(@library), notice: "Library was successfully created." }
        format.json { render :show, status: :created, location: @library }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @library.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /libraries/1 or /libraries/1.json
  def update
    respond_to do |format|
      if @library.update(library_params)
        format.html { redirect_to library_url(@library), notice: "Library was successfully updated." }
        format.json { render :show, status: :ok, location: @library }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @library.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /libraries/1 or /libraries/1.json
  def destroy
    @library.destroy

    respond_to do |format|
      format.html { redirect_to libraries_url, notice: "Library was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_library
      @library = Library.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def library_params
      params.fetch(:library, {})
    end
end

app/helpers/libraries_helper.rb
module LibrariesHelper
end

app/views/libraries/_form.html.erb
<%= form_with(model: library) do |form| %>
  <% if library.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(library.errors.count, "error") %> prohibited this library from being saved:</h2>

      <ul>
        <% library.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/libraries/_library.html.erb
<div id="<%= dom_id library %>">
</div>

app/views/libraries/edit.html.erb
<h1>Editing library</h1>

<%= render "form", library: @library %>

<br>

<div>
  <%= link_to "Show this library", @library %> |
  <%= link_to "Back to libraries", libraries_path %>
</div>

app/views/libraries/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Libraries</h1>

<div id="libraries">
  <% @libraries.each do |library| %>
    <%= render library %>
    <p>
      <%= link_to "Show this library", library %>
    </p>
  <% end %>
</div>

<%= link_to "New library", new_library_path %>

app/views/libraries/new.html.erb
<h1>New library</h1>

<%= render "form", library: @library %>

<br>

<div>
  <%= link_to "Back to libraries", libraries_path %>
</div>

app/views/libraries/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @library %>

<div>
  <%= link_to "Edit this library", edit_library_path(@library) %> |
  <%= link_to "Back to libraries", libraries_path %>

  <%= button_to "Destroy this library", @library, method: :delete %>
</div>